### ISSUE TITLE
APPPrinter.m:191:8: Implicit declaration of function 'CDV_IsIPad' is invalid in C99

### ISSUE THREAD

**Issue by steveetm** [Telerik-Verified-Plugins/Printer#1]
See [https://issues.apache.org/jira/browse/CB-7753](url)

Any hint? atm I'm using the old functions inlined, but I think there was a good reason to remove this.

**Comment by EddyVerbruggen** [comment]
There's [a PR in the upstream repo](https://github.com/katzer/cordova-plugin-printer/pull/79) which we could cherry-pick.

**Comment by EddyVerbruggen** [comment]
OK, this has been fixed in 0.7.1, just released.
